### ISSUE TITLE
Attempting to mine Crimson Stem on the server resulted in a connection interruption and inability to re-enter the server

### ISSUE THREAD

**Issue by DarkgreenWorld** [Jboymercs/nether_backport#15]
If you try to enter again, it will display: internal server error.
Of course, this will not cause the server itself to crash.
The following is the backend output of the server:
`[12:43:51] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[12:43:51] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Colliding entity with block
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.handler$zzp000$newWhileLoop(MinecraftServer.java:2301) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:493) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: net.minecraft.util.ReportedException: Colliding entity with block
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:971) ~[vg.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70091_d(GCEntityPlayerMP.java:57) ~[GCEntityPlayerMP.class:unspecified]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:545) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) ~[lk$a.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at com.unseen.nb.common.blocks.base.BlockVineBase.func_180634_a(BlockVineBase.java:155) ~[BlockVineBase.class:?]
        at net.minecraft.entity.Entity.func_145775_I(Entity.java:1044) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:964) ~[vg.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70091_d(GCEntityPlayerMP.java:57) ~[GCEntityPlayerMP.class:unspecified]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:545) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) ~[lk$a.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 6 more
[12:43:51] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[12:43:51] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /117.37.100.232:40444
net.minecraft.util.ReportedException: Colliding entity with block
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.handler$zzp000$newWhileLoop(MinecraftServer.java:2301) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:493) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at com.unseen.nb.common.blocks.base.BlockVineBase.func_180634_a(BlockVineBase.java:155) ~[BlockVineBase.class:?]
        at net.minecraft.entity.Entity.func_145775_I(Entity.java:1044) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:964) ~[vg.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70091_d(GCEntityPlayerMP.java:57) ~[GCEntityPlayerMP.class:unspecified]
        at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.handler$zgc000$travel(EntityPlayer.java:43637) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 10 more
[12:43:51] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: 111 lost connection: Internal server error
[12:43:51] [Server thread/INFO] [minecraft/DedicatedServer]: 111 left the game`

**Comment by DarkgreenWorld** [comment]
In single player games, it is characterized by extremely slow digging speed and no dropped items. Through testing, it can be proven that it is not caused by conflicts with other mods, as it works the same way when working alone.

**Comment by Jboymercs** [comment]
This is the vine crash called upon elsewhere, fixed in 0.5
